### ISSUE TITLE
Does Length.Parse not support micrometers ?

### ISSUE THREAD

**Issue by sgily** [JohanLarsson/Gu.Units#26]
Following code in version 0.10.4.0 throws an Exception:  Could not parse the unit value from: 100um

`Length umString = Length.Parse("100um");`

However strings with mm, cm, nm etc work fine. Is there something i'm missing ?

Thanks,
Stas

**Comment by JohanLarsson** [comment]
Does it work with `Length umString = Length.Parse("100 μm");`?

**Comment by sgily** [comment]
No neither um or μm, with or without the space works for me, same exception message as mentioned above.

**Comment by JohanLarsson** [comment]
Ok, looks like I dumbed something. The parsing is pretty dumb overall, I was playing around.
I'll have a look.

**Comment by sgily** [comment]
No worries, not super critical i guess. Keep up the good work though, great library :)

**Comment by JohanLarsson** [comment]
The problem is I mixed up:
http://www.fileformat.info/info/unicode/char/00b5/index.htm
http://www.fileformat.info/info/unicode/char/03BC/index.htm

Gonna special case it so that both are ok to not break things.

**Comment by JohanLarsson** [comment]
Is this issue stopping you? I can release now if so if not I'll have a look at other similar cases like ohm and capital omega.

**Comment by sgily** [comment]
Non-blocker, i'll get around until the new release, thanks !

**Comment by JohanLarsson** [comment]
Released now.
